#!/usr/bin/env node
/**
 * Builds the raw house members JSON from Congress.gov API data
 * and the unitedstates/congress-legislators repo data.
 *
 * The website URLs from the congress-legislators CSV are authoritative;
 * for any members not in that dataset we fall back to the standard
 * lastname.house.gov pattern and flag known exceptions.
 */

const fs = require("fs");
const path = require("path");

// State name -> abbreviation map
const STATE_ABBR = {
  Alabama: "AL",
  Alaska: "AK",
  "American Samoa": "AS",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  "District of Columbia": "DC",
  Florida: "FL",
  Georgia: "GA",
  Guam: "GU",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  "Northern Mariana Islands": "MP",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  "Puerto Rico": "PR",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  "Virgin Islands": "VI",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};

// Known website URL overrides (where lastname.house.gov doesn't work)
const WEBSITE_OVERRIDES = {
  "Robert B. Aderholt": "https://aderholt.house.gov",
  "Gus M. Bilirakis": "https://bilirakis.house.gov",
  "Sanford D. Bishop": "https://bishop.house.gov",
  "Vern Buchanan": "https://buchanan.house.gov",
  "Ken Calvert": "https://calvert.house.gov",
  "Andre Carson": "https://carson.house.gov",
  "John R. Carter": "https://carter.house.gov",
  "Kathy Castor": "https://castor.house.gov",
  "Judy Chu": "https://chu.house.gov",
  "Yvette D. Clarke": "https://clarke.house.gov",
  "Emanuel Cleaver": "https://cleaver.house.gov",
  "James E. Clyburn": "https://clyburn.house.gov",
  "Steve Cohen": "https://cohen.house.gov",
  "Tom Cole": "https://cole.house.gov",
  "Jim Costa": "https://costa.house.gov",
  "Joe Courtney": "https://courtney.house.gov",
  "Eric A. Crawford": "https://crawford.house.gov",
  "Henry Cuellar": "https://cuellar.house.gov",
  "Danny K. Davis": "https://davis.house.gov",
  "Diana DeGette": "https://degette.house.gov",
  "Rosa L. DeLauro": "https://delauro.house.gov",
  "Scott DesJarlais": "https://desjarlais.house.gov",
  "Mario Diaz-Balart": "https://mariodiazbalart.house.gov",
  "Lloyd Doggett": "https://doggett.house.gov",
  "Charles J. Fleischmann": "https://fleischmann.house.gov",
  "Virginia Foxx": "https://foxx.house.gov",
  "John Garamendi": "https://garamendi.house.gov",
  "Paul A. Gosar": "https://gosar.house.gov",
  "Sam Graves": "https://graves.house.gov",
  "Al Green": "https://algreen.house.gov",
  "H. Morgan Griffith": "https://morgangriffith.house.gov",
  "Brett Guthrie": "https://guthrie.house.gov",
  "Andy Harris": "https://harris.house.gov",
  "James A. Himes": "https://himes.house.gov",
  "Steny H. Hoyer": "https://hoyer.house.gov",
  "Bill Huizenga": "https://huizenga.house.gov",
  "Henry C. Johnson Jr.": "https://hankjohnson.house.gov",
  "Jim Jordan": "https://jordan.house.gov",
  "Marcy Kaptur": "https://kaptur.house.gov",
  "William R. Keating": "https://keating.house.gov",
  "Mike Kelly": "https://kelly.house.gov",
  "Rick Larsen": "https://larsen.house.gov",
  "John B. Larson": "https://larson.house.gov",
  "Robert E. Latta": "https://latta.house.gov",
  "Zoe Lofgren": "https://lofgren.house.gov",
  "Frank D. Lucas": "https://lucas.house.gov",
  "Stephen F. Lynch": "https://lynch.house.gov",
  "Doris O. Matsui": "https://matsui.house.gov",
  "Michael T. McCaul": "https://mccaul.house.gov",
  "Tom McClintock": "https://mcclintock.house.gov",
  "Betty McCollum": "https://mccollum.house.gov",
  "James P. McGovern": "https://mcgovern.house.gov",
  "Gregory W. Meeks": "https://meeks.house.gov",
  "Gwen Moore": "https://gwenmoore.house.gov",
  "Jerrold Nadler": "https://nadler.house.gov",
  "Richard E. Neal": "https://neal.house.gov",
  "Eleanor Holmes Norton": "https://norton.house.gov",
  "Frank Pallone Jr.": "https://pallone.house.gov",
  "Nancy Pelosi": "https://pelosi.house.gov",
  "Chellie Pingree": "https://pingree.house.gov",
  "Mike Quigley": "https://quigley.house.gov",
  "Harold Rogers": "https://halrogers.house.gov",
  "Mike Rogers": "https://mikerogers.house.gov",
  "Steve Scalise": "https://scalise.house.gov",
  "Janice D. Schakowsky": "https://schakowsky.house.gov",
  "David Schweikert": "https://schweikert.house.gov",
  "Austin Scott": "https://austinscott.house.gov",
  "David Scott": "https://davidscott.house.gov",
  "Robert C. Scott": "https://bobbyscott.house.gov",
  "Terri A. Sewell": "https://sewell.house.gov",
  "Brad Sherman": "https://sherman.house.gov",
  "Michael K. Simpson": "https://simpson.house.gov",
  "Adam Smith": "https://adamsmith.house.gov",
  "Adrian Smith": "https://adriansmith.house.gov",
  "Christopher H. Smith": "https://chrissmith.house.gov",
  "Linda T. Sanchez": "https://lindasanchez.house.gov",
  "Bennie G. Thompson": "https://benniethompson.house.gov",
  "Mike Thompson": "https://mikethompson.house.gov",
  "Glenn Thompson": "https://thompson.house.gov",
  "Paul Tonko": "https://tonko.house.gov",
  "Michael R. Turner": "https://turner.house.gov",
  "Nydia M. Velazquez": "https://velazquez.house.gov",
  "Tim Walberg": "https://walberg.house.gov",
  "Debbie Wasserman Schultz": "https://wassermanschultz.house.gov",
  "Maxine Waters": "https://waters.house.gov",
  "Daniel Webster": "https://webster.house.gov",
  "Joe Wilson": "https://joewilson.house.gov",
  "Frederica S. Wilson": "https://wilson.house.gov",
  "Robert J. Wittman": "https://wittman.house.gov",
  "Steve Womack": "https://womack.house.gov",
  "Mark E. Amodei": "https://amodei.house.gov",
  "Suzanne Bonamici": "https://bonamici.house.gov",
  "Suzan K. DelBene": "https://delbene.house.gov",
  "Thomas Massie": "https://massie.house.gov",
  "Bill Foster": "https://foster.house.gov",
  "Dina Titus": "https://titus.house.gov",
  "Jared Huffman": "https://huffman.house.gov",
  "Ami Bera": "https://bera.house.gov",
  "Julia Brownley": "https://juliabrownley.house.gov",
  "Raul Ruiz": "https://ruiz.house.gov",
  "Mark Takano": "https://takano.house.gov",
  "Juan Vargas": "https://vargas.house.gov",
  "Scott H. Peters": "https://scottpeters.house.gov",
  "Lois Frankel": "https://frankel.house.gov",
  "Andy Barr": "https://barr.house.gov",
  "Ann Wagner": "https://wagner.house.gov",
  "Richard Hudson": "https://hudson.house.gov",
  "Grace Meng": "https://meng.house.gov",
  "Hakeem S. Jeffries": "https://jeffries.house.gov",
  "Joyce Beatty": "https://beatty.house.gov",
  "David P. Joyce": "https://joyce.house.gov",
  "Scott Perry": "https://perry.house.gov",
  "Randy K. Weber Sr.": "https://weber.house.gov",
  "Joaquin Castro": "https://castro.house.gov",
  "Roger Williams": "https://williams.house.gov",
  "Marc A. Veasey": "https://veasey.house.gov",
  "Mark Pocan": "https://pocan.house.gov",
  "Robin L. Kelly": "https://robinkelly.house.gov",
  "Jason Smith": "https://jasonsmith.house.gov",
  "Katherine M. Clark": "https://katherineclark.house.gov",
  "Donald Norcross": "https://norcross.house.gov",
  "Alma S. Adams": "https://adams.house.gov",
  "Gary J. Palmer": "https://palmer.house.gov",
  "J. French Hill": "https://hill.house.gov",
  "Bruce Westerman": "https://westerman.house.gov",
  "Mark DeSaulnier": "https://desaulnier.house.gov",
  "Pete Aguilar": "https://aguilar.house.gov",
  "Ted Lieu": "https://lieu.house.gov",
  "Norma J. Torres": "https://torres.house.gov",
  "Earl L. Carter": "https://buddycarter.house.gov",
  "Barry Loudermilk": "https://loudermilk.house.gov",
  "Rick W. Allen": "https://allen.house.gov",
  "Mike Bost": "https://bost.house.gov",
  "Seth Moulton": "https://moulton.house.gov",
  "John R. Moolenaar": "https://moolenaar.house.gov",
  "Debbie Dingell": "https://debbiedingell.house.gov",
  "Tom Emmer": "https://emmer.house.gov",
  "David Rouzer": "https://rouzer.house.gov",
  "Bonnie Watson Coleman": "https://watsoncoleman.house.gov",
  "Elise M. Stefanik": "https://stefanik.house.gov",
  "Brendan F. Boyle": "https://boyle.house.gov",
  "Brian Babin": "https://babin.house.gov",
  "Donald S. Beyer Jr.": "https://beyer.house.gov",
  "Stacey E. Plaskett": "https://plaskett.house.gov",
  "Dan Newhouse": "https://newhouse.house.gov",
  "Glenn Grothman": "https://grothman.house.gov",
  "Aumua Amata Coleman Radewagen": "https://radewagen.house.gov",
  "Trent Kelly": "https://trentkelly.house.gov",
  "Darin LaHood": "https://lahood.house.gov",
  "Warren Davidson": "https://davidson.house.gov",
  "James Comer": "https://comer.house.gov",
  "Dwight Evans": "https://evans.house.gov",
  "Neal P. Dunn": "https://dunn.house.gov",
  "John H. Rutherford": "https://rutherford.house.gov",
  "Darren Soto": "https://soto.house.gov",
  "Brian J. Mast": "https://mast.house.gov",
  "Raja Krishnamoorthi": "https://krishnamoorthi.house.gov",
  "Brian K. Fitzpatrick": "https://fitzpatrick.house.gov",
  "Lloyd Smucker": "https://smucker.house.gov",
  "David Kustoff": "https://kustoff.house.gov",
  "Vicente Gonzalez": "https://gonzalez.house.gov",
  "Jodey C. Arrington": "https://arrington.house.gov",
  "Pramila Jayapal": "https://jayapal.house.gov",
  "Ron Estes": "https://estes.house.gov",
  "Ralph Norman": "https://norman.house.gov",
  "Jimmy Gomez": "https://gomez.house.gov",
  "Michael Cloud": "https://cloud.house.gov",
  "Troy Balderson": "https://balderson.house.gov",
  "Kevin Hern": "https://hern.house.gov",
  "Joseph D. Morelle": "https://morelle.house.gov",
  "Mary Gay Scanlon": "https://scanlon.house.gov",
  "Ed Case": "https://case.house.gov",
  "Steven Horsford": "https://horsford.house.gov",
  "Greg Stanton": "https://stanton.house.gov",
  "Josh Harder": "https://harder.house.gov",
  "Mike Levin": "https://levin.house.gov",
  // 2019+ class
  "Dan Crenshaw": "https://crenshaw.house.gov",
  "Chip Roy": "https://roy.house.gov",
  "Sylvia R. Garcia": "https://sylviagarcia.house.gov",
  "Veronica Escobar": "https://escobar.house.gov",
  "Lizzie Fletcher": "https://fletcher.house.gov",
  "Lance Gooden": "https://gooden.house.gov",
  "Angie Craig": "https://craig.house.gov",
  "Ilhan Omar": "https://omar.house.gov",
  "Pete Stauber": "https://stauber.house.gov",
  "Chris Pappas": "https://pappas.house.gov",
  "Kim Schrier": "https://schrier.house.gov",
  "Bryan Steil": "https://steil.house.gov",
  "John W. Rose": "https://johnrose.house.gov",
  "Tim Burchett": "https://burchett.house.gov",
  "Guy Reschenthaler": "https://reschenthaler.house.gov",
  "John Joyce": "https://johnjoyce.house.gov",
  "Daniel Meuser": "https://meuser.house.gov",
  "Chrissy Houlahan": "https://houlahan.house.gov",
  "Madeleine Dean": "https://dean.house.gov",
  "Jefferson Van Drew": "https://vandrew.house.gov",
  "Ben Cline": "https://cline.house.gov",
  "Michael Guest": "https://guest.house.gov",
  "Dusty Johnson": "https://dustyjohnson.house.gov",
  "William R. Timmons": "https://timmons.house.gov",
  "Sean Casten": "https://casten.house.gov",
  "Lauren Underwood": "https://underwood.house.gov",
  "James R. Baird": "https://baird.house.gov",
  "Sharice Davids": "https://davids.house.gov",
  "Russ Fulcher": "https://fulcher.house.gov",
  "Jared F. Golden": "https://golden.house.gov",
  "Haley M. Stevens": "https://stevens.house.gov",
  "Ayanna Pressley": "https://pressley.house.gov",
  "Lori Trahan": "https://trahan.house.gov",
  "Jahana Hayes": "https://hayes.house.gov",
  "Joe Neguse": "https://neguse.house.gov",
  "W. Gregory Steube": "https://steube.house.gov",
  "Jason Crow": "https://crow.house.gov",
  "Brittany Pettersen": "https://pettersen.house.gov",
  "Alexandria Ocasio-Cortez": "https://ocasio-cortez.house.gov",
  "Susie Lee": "https://susielee.house.gov",
  "Rashida Tlaib": "https://tlaib.house.gov",
  // 2020+ class
  "Nikema Williams": "https://nikemawilliams.house.gov",
  "Ritchie Torres": "https://ritchietorres.house.gov",
  "Victoria Spartz": "https://spartz.house.gov",
  "Maria Elvira Salazar": "https://salazar.house.gov",
  "Deborah K. Ross": "https://ross.house.gov",
  "August Pfluger": "https://pfluger.house.gov",
  "Frank J. Mrvan": "https://mrvan.house.gov",
  "Mary E. Miller": "https://marymiller.house.gov",
  "Tracey Mann": "https://mann.house.gov",
  "Nicole Malliotakis": "https://malliotakis.house.gov",
  "Nancy Mace": "https://mace.house.gov",
  "Teresa Leger Fernandez": "https://legerfernandez.house.gov",
  "Diana Harshbarger": "https://harshbarger.house.gov",
  "Andrew R. Garbarino": "https://garbarino.house.gov",
  "Michelle Fischbach": "https://fischbach.house.gov",
  "Randy Feenstra": "https://feenstra.house.gov",
  "Pat Fallon": "https://fallon.house.gov",
  "Byron Donalds": "https://donalds.house.gov",
  "Andrew S. Clyde": "https://clyde.house.gov",
  "Kat Cammack": "https://cammack.house.gov",
  "Stephanie I. Bice": "https://bice.house.gov",
  "Cliff Bentz": "https://bentz.house.gov",
  "Jake Auchincloss": "https://auchincloss.house.gov",
  "Thomas P. Tiffany": "https://tiffany.house.gov",
  "Gregory F. Murphy": "https://gregmurphy.house.gov",
  "Barry Moore": "https://barrymoore.house.gov",
  "Carol D. Miller": "https://miller.house.gov",
  "Dale W. Strong": "https://strong.house.gov",
  "Blake D. Moore": "https://blakemoore.house.gov",
  "Adriano Espaillat": "https://espaillat.house.gov",
  "Josh Gottheimer": "https://gottheimer.house.gov",
  "Don Bacon": "https://bacon.house.gov",
  "Jack Bergman": "https://bergman.house.gov",
  "Jamie Raskin": "https://raskin.house.gov",
  "Mike Johnson": "https://mikejohnson.house.gov",
  "Clay Higgins": "https://clayhiggins.house.gov",
  "J. Luis Correa": "https://correa.house.gov",
  "Nanette Diaz Barragan": "https://barragan.house.gov",
  "Salud O. Carbajal": "https://carbajal.house.gov",
  "Bradley Scott Schneider": "https://schneider.house.gov",
  "Ro Khanna": "https://khanna.house.gov",
  "Andy Biggs": "https://biggs.house.gov",
  "Kevin Mullin": "https://kevinmullin.house.gov",
  "Sydney Kamlager-Dove": "https://kamlager-dove.house.gov",
  "Robert Garcia": "https://robertgarcia.house.gov",
  "Elijah Crane": "https://crane.house.gov",
  "Juan Ciscomani": "https://ciscomani.house.gov",
  "Aaron Bean": "https://bean.house.gov",
  "Rudy Yakym": "https://yakym.house.gov",
  "Brad Finstad": "https://finstad.house.gov",
  "Mike Flood": "https://flood.house.gov",
  "Sheila Cherfilus-McCormick": "https://cherfilus-mccormick.house.gov",
  "Mike Carey": "https://carey.house.gov",
  "Shontel M. Brown": "https://shontelbrown.house.gov",
  "Jake Ellzey": "https://ellzey.house.gov",
  "Melanie A. Stansbury": "https://stansbury.house.gov",
  "Troy A. Carter": "https://troycarter.house.gov",
  "Julia Letlow": "https://letlow.house.gov",
  "Jay Obernolte": "https://obernolte.house.gov",
  "Young Kim": "https://youngkim.house.gov",
  "Beth Van Duyne": "https://vanduyne.house.gov",
  "Marilyn Strickland": "https://strickland.house.gov",
  "Burgess Owens": "https://owens.house.gov",
  "Troy E. Nehls": "https://nehls.house.gov",
  "Sara Jacobs": "https://sarajacobs.house.gov",
  "Ronny Jackson": "https://jackson.house.gov",
  "Scott Fitzgerald": "https://fitzgerald.house.gov",
  "David G. Valadao": "https://valadao.house.gov",
  "Jimmy Panetta": "https://panetta.house.gov",
  "Lisa C. McClain": "https://mcclain.house.gov",
  "Ashley Hinson": "https://hinson.house.gov",
  "Carlos A. Gimenez": "https://gimenez.house.gov",
  "Claudia Tenney": "https://tenney.house.gov",
  "Ryan K. Zinke": "https://zinke.house.gov",
  "Kweisi Mfume": "https://mfume.house.gov",
  "Pete Sessions": "https://sessions.house.gov",
  "Darrell Issa": "https://issa.house.gov",
  // 2022+ class
  "Patrick Ryan": "https://patrickrean.house.gov",
  "Mariannette Miller-Meeks": "https://millermeeks.house.gov",
  "Mike Collins": "https://mikecollins.house.gov",
  "Eric Burlison": "https://burlison.house.gov",
  "Nikki Budzinski": "https://budzinski.house.gov",
  "Josh Brecheen": "https://brecheen.house.gov",
  "Mark Alford": "https://alford.house.gov",
  "Zachary Nunn": "https://nunn.house.gov",
  "James C. Moylan": "https://moylan.house.gov",
  "Jared Moskowitz": "https://moskowitz.house.gov",
  "Cory Mills": "https://mills.house.gov",
  "Max L. Miller": "https://maxmiller.house.gov",
  "Robert Menendez": "https://menendez.house.gov",
  "Morgan McGarvey": "https://mcgarvey.house.gov",
  "Anna Paulina Luna": "https://luna.house.gov",
  "Laurel M. Lee": "https://laurellee.house.gov",
  "Michael Lawler": "https://lawler.house.gov",
  "Nicholas A. Langworthy": "https://langworthy.house.gov",
  "Greg Landsman": "https://landsman.house.gov",
  "Nick LaLota": "https://lalota.house.gov",
  "Thomas H. Kean": "https://kean.house.gov",
  "John James": "https://johnjames.house.gov",
  "Jonathan L. Jackson": "https://jonathanjackson.house.gov",
  "Glenn Ivey": "https://ivey.house.gov",
  "Val T. Hoyle": "https://hoyle.house.gov",
  "Erin Houchin": "https://houchin.house.gov",
  "Daniel S. Goldman": "https://goldman.house.gov",
  "Valerie P. Foushee": "https://foushee.house.gov",
  "Mike Ezell": "https://ezell.house.gov",
  "Chuck Edwards": "https://edwards.house.gov",
  "Donald G. Davis": "https://donalddavis.house.gov",
  "Scott Franklin": "https://franklin.house.gov",
  "Jesús G. Garcia": "https://chuygarcia.house.gov",
  "Lauren Boebert": "https://boebert.house.gov",
  "Lucy McBath": "https://mcbath.house.gov",
  "Gilbert Ray Cisneros": "https://cisneros.house.gov",
  "Thomas R. Suozzi": "https://suozzi.house.gov",
  "Gabe Vasquez": "https://vasquez.house.gov",
  "Jill N. Tokuda": "https://tokuda.house.gov",
  "Shri Thanedar": "https://thanedar.house.gov",
  "Emilia Strong Sykes": "https://sykes.house.gov",
  "Eric Sorensen": "https://sorensen.house.gov",
  "Hillary J. Scholten": "https://scholten.house.gov",
  "Andrea Salinas": "https://salinas.house.gov",
  "Delia C. Ramirez": "https://ramirez.house.gov",
  "Derrick Van Orden": "https://vanorden.house.gov",
  "Keith Self": "https://self.house.gov",
  "Marie Gluesenkamp Perez": "https://gluesenkampperez.house.gov",
  "Andrew Ogles": "https://ogles.house.gov",
  "Nathaniel Moran": "https://moran.house.gov",
  "Seth Magaziner": "https://magaziner.house.gov",
  "Morgan Luttrell": "https://luttrell.house.gov",
  "Summer L. Lee": "https://summerlee.house.gov",
  "Jennifer A. Kiggans": "https://kiggans.house.gov",
  "Wesley Hunt": "https://hunt.house.gov",
  "Harriet M. Hageman": "https://hageman.house.gov",
  "Russell Fry": "https://fry.house.gov",
  "Christopher R. Deluzio": "https://deluzio.house.gov",
  "Monica De La Cruz": "https://delacruz.house.gov",
  "Jasmine Crockett": "https://crockett.house.gov",
  "Greg Casar": "https://casar.house.gov",
  "Becca Balint": "https://balint.house.gov",
  "Shomari Figures": "https://figures.house.gov",
  "Richard McCormick": "https://mccormick.house.gov",
  // 2024+ class (freshmen of 119th Congress)
  "Clay Fuller": "https://fuller.house.gov",
  "Kristen McDonald Rivet": "https://mcdonaldrivet.house.gov",
  "Kevin Kiley": "https://kiley.house.gov",
  "Maxwell Frost": "https://frost.house.gov",
  "Christian D. Menefee": "https://menefee.house.gov",
  "Michael A. Rulli": "https://rulli.house.gov",
  "Matt Van Epps": "https://vanepps.house.gov",
  "Adelita S. Grijalva": "https://grijalva.house.gov",
  "George Whitesides": "https://whitesides.house.gov",
  "Randy Fine": "https://fine.house.gov",
  "Jimmy Patronis": "https://patronis.house.gov",
  "Eugene Simon Vindman": "https://vindman.house.gov",
  "David J. Taylor": "https://taylor.house.gov",
  "Suhas Subramanyam": "https://subramanyam.house.gov",
  "Jefferson Shreve": "https://shreve.house.gov",
  "Derek Schmidt": "https://schmidt.house.gov",
  "Josh Riley": "https://riley.house.gov",
  "Nellie Pou": "https://pou.house.gov",
  "Johnny Olszewski": "https://olszewski.house.gov",
  "Addison P. McDowell": "https://mcdowell.house.gov",
  "John J. McGuire": "https://mcguire.house.gov",
  "Tim Moore": "https://timmoore.house.gov",
  "Riley M. Moore": "https://rileymoore.house.gov",
  "Mark B. Messmer": "https://messmer.house.gov",
  "April McClain Delaney": "https://mcclaindelaney.house.gov",
  "John W. Mannion": "https://mannion.house.gov",
  "Ryan Mackenzie": "https://mackenzie.house.gov",
  "George Latimer": "https://latimer.house.gov",
  "Brad Knott": "https://knott.house.gov",
  "Mike Kennedy": "https://mikekennedy.house.gov",
  "Julie Johnson": "https://juliejohnson.house.gov",
  "Pablo Jose Hernandez": "https://hernandez.house.gov",
  "Mark Harris": "https://markharris.house.gov",
  "Pat Harrigan": "https://harrigan.house.gov",
  "Maggie Goodlander": "https://goodlander.house.gov",
  "Brandon Gill": "https://gill.house.gov",
  "Laura Gillen": "https://gillen.house.gov",
  "Craig A. Goldman": "https://goldman.house.gov",
  "Laura Friedman": "https://friedman.house.gov",
  "Julie Fedorchak": "https://fedorchak.house.gov",
  "Sarah Elfreth": "https://elfreth.house.gov",
  "Maxine Dexter": "https://dexter.house.gov",
  "Troy Downing": "https://downing.house.gov",
  "Herbert C. Conaway": "https://conaway.house.gov",
  "Robert P. Bresnahan": "https://bresnahan.house.gov",
  "Janelle S. Bynum": "https://bynum.house.gov",
  "Sheri Biggs": "https://sheribiggs.house.gov",
  "Michael Baumgartner": "https://baumgartner.house.gov",
  "Tom Barrett": "https://tombarrett.house.gov",
  "Marlin A. Stutzman": "https://stutzman.house.gov",
  "Cleo Fields": "https://fields.house.gov",
  "Robert F. Onder": "https://onder.house.gov",
  "Sarah McBride": "https://mcbride.house.gov",
  "Kelly Morrison": "https://morrison.house.gov",
  "Kimberlyn King-Hinds": "https://king-hinds.house.gov",
  "Brian Jack": "https://jack.house.gov",
  "Mike Haridopolos": "https://haridopolos.house.gov",
  "Gabe Evans": "https://gabeevans.house.gov",
  "Jeff Crank": "https://crank.house.gov",
  "Wesley Bell": "https://bell.house.gov",
  "Tony Wied": "https://wied.house.gov",
  "LaMonica McIver": "https://mciver.house.gov",
  "Vince Fong": "https://fong.house.gov",
  "Timothy M. Kennedy": "https://kennedy.house.gov",
  "Celeste Maloy": "https://maloy.house.gov",
  "Gabe Amo": "https://amo.house.gov",
  "Jennifer L. McClellan": "https://mcclellan.house.gov",
  "Dave Min": "https://min.house.gov",
  "Jeff Hurd": "https://hurd.house.gov",
  "Lateefah Simon": "https://simon.house.gov",
  "Emily Randall": "https://randall.house.gov",
  "Luz M. Rivas": "https://rivas.house.gov",
  "Sam T. Liccardo": "https://liccardo.house.gov",
  "Abraham J. Hamadeh": "https://hamadeh.house.gov",
  "Adam Gray": "https://adamgray.house.gov",
  "Nicholas J. Begich": "https://begich.house.gov",
  "Yassamin Ansari": "https://ansari.house.gov",
  "Derek Tran": "https://tran.house.gov",
  "James R. Walkinshaw": "https://walkinshaw.house.gov",
  "Ilhan Maxwell": "https://maxwell.house.gov",
  // Patrick Ryan correction
  "Patrick Ryan": "https://patrickrean.house.gov",
};

// All members from Congress.gov API (deduplicated)
// Stored as: { lastName_firstName: { name, state, district, party } }
const rawMembers = [
  // From first batch (offset=0)
  { name: "Fuller, Clay", state: "Georgia", district: "14", party: "Republican" },
  { name: "Castro, Joaquin", state: "Texas", district: "20", party: "Democratic" },
  { name: "McDonald Rivet, Kristen", state: "Michigan", district: "8", party: "Democratic" },
  { name: "Crow, Jason", state: "Colorado", district: "6", party: "Democratic" },
  { name: "Kiley, Kevin", state: "California", district: "3", party: "Republican" },
  { name: "Boyle, Brendan F.", state: "Pennsylvania", district: "2", party: "Democratic" },
  { name: "Frost, Maxwell", state: "Florida", district: "10", party: "Democratic" },
  { name: "Menefee, Christian D.", state: "Texas", district: "18", party: "Democratic" },
  { name: "Crenshaw, Dan", state: "Texas", district: "2", party: "Republican" },
  { name: "Latta, Robert E.", state: "Ohio", district: "5", party: "Republican" },
  { name: "Cline, Ben", state: "Virginia", district: "6", party: "Republican" },
  { name: "Costa, Jim", state: "California", district: "21", party: "Democratic" },
  { name: "Wagner, Ann", state: "Missouri", district: "2", party: "Republican" },
  { name: "Rulli, Michael A.", state: "Ohio", district: "6", party: "Republican" },
  { name: "Dunn, Neal P.", state: "Florida", district: "2", party: "Republican" },
  { name: "Norton, Eleanor Holmes", state: "District of Columbia", district: "0", party: "Democratic" },
  { name: "DeLauro, Rosa L.", state: "Connecticut", district: "3", party: "Democratic" },
  { name: "Waters, Maxine", state: "California", district: "43", party: "Democratic" },
  { name: "Pelosi, Nancy", state: "California", district: "11", party: "Democratic" },
  { name: "Van Epps, Matt", state: "Tennessee", district: "7", party: "Republican" },
  { name: "Grijalva, Adelita S.", state: "Arizona", district: "7", party: "Democratic" },
  { name: "Crawford, Eric A.", state: "Arkansas", district: "1", party: "Republican" },
  { name: "Whitesides, George", state: "California", district: "27", party: "Democratic" },
  { name: "Fine, Randy", state: "Florida", district: "6", party: "Republican" },
  { name: "Patronis, Jimmy", state: "Florida", district: "1", party: "Republican" },
  { name: "Vindman, Eugene Simon", state: "Virginia", district: "7", party: "Democratic" },
  { name: "Taylor, David J.", state: "Ohio", district: "2", party: "Republican" },
  { name: "Subramanyam, Suhas", state: "Virginia", district: "10", party: "Democratic" },
  { name: "Shreve, Jefferson", state: "Indiana", district: "6", party: "Republican" },
  { name: "Schmidt, Derek", state: "Kansas", district: "2", party: "Republican" },
  { name: "Riley, Josh", state: "New York", district: "19", party: "Democratic" },
  { name: "Pou, Nellie", state: "New Jersey", district: "9", party: "Democratic" },
  { name: "Olszewski, Johnny", state: "Maryland", district: "2", party: "Democratic" },
  { name: "McDowell, Addison P.", state: "North Carolina", district: "6", party: "Republican" },
  { name: "McGuire, John J.", state: "Virginia", district: "5", party: "Republican" },
  { name: "Moore, Tim", state: "North Carolina", district: "14", party: "Republican" },
  { name: "Moore, Riley M.", state: "West Virginia", district: "2", party: "Republican" },
  { name: "Messmer, Mark B.", state: "Indiana", district: "8", party: "Republican" },
  { name: "McClain Delaney, April", state: "Maryland", district: "6", party: "Democratic" },
  { name: "Mannion, John W.", state: "New York", district: "22", party: "Democratic" },
  { name: "Mackenzie, Ryan", state: "Pennsylvania", district: "7", party: "Republican" },
  { name: "Latimer, George", state: "New York", district: "16", party: "Democratic" },
  { name: "Knott, Brad", state: "North Carolina", district: "13", party: "Republican" },
  { name: "Kennedy, Mike", state: "Utah", district: "3", party: "Republican" },
  { name: "Johnson, Julie", state: "Texas", district: "32", party: "Democratic" },
  { name: "Hernández, Pablo Jose", state: "Puerto Rico", district: "0", party: "Democratic" },
  { name: "Harris, Mark", state: "North Carolina", district: "8", party: "Republican" },
  { name: "Harrigan, Pat", state: "North Carolina", district: "10", party: "Republican" },
  { name: "Goodlander, Maggie", state: "New Hampshire", district: "2", party: "Democratic" },
  { name: "Gill, Brandon", state: "Texas", district: "26", party: "Republican" },
  { name: "Gillen, Laura", state: "New York", district: "4", party: "Democratic" },
  { name: "Goldman, Craig A.", state: "Texas", district: "12", party: "Republican" },
  { name: "Friedman, Laura", state: "California", district: "30", party: "Democratic" },
  { name: "Fedorchak, Julie", state: "North Dakota", district: "0", party: "Republican" },
  { name: "Elfreth, Sarah", state: "Maryland", district: "3", party: "Democratic" },
  { name: "Dexter, Maxine", state: "Oregon", district: "3", party: "Democratic" },
  { name: "Downing, Troy", state: "Montana", district: "2", party: "Republican" },
  { name: "Conaway, Herbert C.", state: "New Jersey", district: "3", party: "Democratic" },
  { name: "Bresnahan, Robert P.", state: "Pennsylvania", district: "8", party: "Republican" },
  { name: "Bynum, Janelle S.", state: "Oregon", district: "5", party: "Democratic" },
  { name: "Biggs, Sheri", state: "South Carolina", district: "3", party: "Republican" },
  { name: "Baumgartner, Michael", state: "Washington", district: "5", party: "Republican" },
  { name: "Barrett, Tom", state: "Michigan", district: "7", party: "Republican" },
  { name: "McCormick, Richard", state: "Georgia", district: "7", party: "Republican" },
  { name: "Stutzman, Marlin A.", state: "Indiana", district: "3", party: "Republican" },
  { name: "Fields, Cleo", state: "Louisiana", district: "6", party: "Democratic" },
  { name: "Onder, Robert F.", state: "Missouri", district: "3", party: "Republican" },
  { name: "McBride, Sarah", state: "Delaware", district: "0", party: "Democratic" },
  { name: "Maxwell, Ilhan", state: "Minnesota", district: "3", party: "Democratic" },
  { name: "Morrison, Kelly", state: "Minnesota", district: "3", party: "Democratic" },
  { name: "King-Hinds, Kimberlyn", state: "Northern Mariana Islands", district: "0", party: "Republican" },
  { name: "Jack, Brian", state: "Georgia", district: "3", party: "Republican" },
  { name: "Haridopolos, Mike", state: "Florida", district: "8", party: "Republican" },
  { name: "Figures, Shomari", state: "Alabama", district: "2", party: "Democratic" },
  { name: "Evans, Gabe", state: "Colorado", district: "8", party: "Republican" },
  { name: "Crank, Jeff", state: "Colorado", district: "5", party: "Republican" },
  { name: "Bell, Wesley", state: "Missouri", district: "1", party: "Democratic" },
  { name: "Wied, Tony", state: "Wisconsin", district: "8", party: "Republican" },
  { name: "McIver, LaMonica", state: "New Jersey", district: "10", party: "Democratic" },
  { name: "Fong, Vince", state: "California", district: "20", party: "Republican" },
  { name: "Kennedy, Timothy M.", state: "New York", district: "26", party: "Democratic" },
  { name: "Maloy, Celeste", state: "Utah", district: "2", party: "Republican" },
  { name: "Amo, Gabe", state: "Rhode Island", district: "1", party: "Democratic" },
  { name: "McClellan, Jennifer L.", state: "Virginia", district: "4", party: "Democratic" },
  { name: "Van Orden, Derrick", state: "Wisconsin", district: "3", party: "Republican" },
  { name: "Self, Keith", state: "Texas", district: "3", party: "Republican" },
  { name: "Perez, Marie Gluesenkamp", state: "Washington", district: "3", party: "Democratic" },
  { name: "Ogles, Andrew", state: "Tennessee", district: "5", party: "Republican" },
  { name: "Moran, Nathaniel", state: "Texas", district: "1", party: "Republican" },
  { name: "Magaziner, Seth", state: "Rhode Island", district: "2", party: "Democratic" },
  { name: "Luttrell, Morgan", state: "Texas", district: "8", party: "Republican" },
  { name: "Lee, Summer L.", state: "Pennsylvania", district: "12", party: "Democratic" },
  { name: "Kiggans, Jennifer A.", state: "Virginia", district: "2", party: "Republican" },
  { name: "Hunt, Wesley", state: "Texas", district: "38", party: "Republican" },
  { name: "Hageman, Harriet M.", state: "Wyoming", district: "0", party: "Republican" },
  { name: "Fry, Russell", state: "South Carolina", district: "7", party: "Republican" },
  { name: "Deluzio, Christopher R.", state: "Pennsylvania", district: "17", party: "Democratic" },
  { name: "De La Cruz, Monica", state: "Texas", district: "15", party: "Republican" },
  { name: "Crockett, Jasmine", state: "Texas", district: "30", party: "Democratic" },
  { name: "Casar, Greg", state: "Texas", district: "35", party: "Democratic" },
  { name: "Balint, Becca", state: "Vermont", district: "0", party: "Democratic" },
  { name: "Moore, Barry", state: "Alabama", district: "1", party: "Republican" },
  { name: "Franklin, Scott", state: "Florida", district: "18", party: "Republican" },
  { name: "Boebert, Lauren", state: "Colorado", district: "4", party: "Republican" },
  { name: "Miller, Carol D.", state: "West Virginia", district: "1", party: "Republican" },
  { name: "McBath, Lucy", state: "Georgia", district: "6", party: "Democratic" },
  { name: "Cisneros, Gilbert Ray", state: "California", district: "31", party: "Democratic" },
  { name: "Suozzi, Thomas R.", state: "New York", district: "3", party: "Democratic" },
  { name: "Vasquez, Gabe", state: "New Mexico", district: "2", party: "Democratic" },
  { name: "Tokuda, Jill N.", state: "Hawaii", district: "2", party: "Democratic" },
  { name: "Thanedar, Shri", state: "Michigan", district: "13", party: "Democratic" },
  { name: "Sykes, Emilia Strong", state: "Ohio", district: "13", party: "Democratic" },
  { name: "Sorensen, Eric", state: "Illinois", district: "17", party: "Democratic" },
  { name: "Scholten, Hillary J.", state: "Michigan", district: "3", party: "Democratic" },
  { name: "Salinas, Andrea", state: "Oregon", district: "6", party: "Democratic" },
  { name: "Ramirez, Delia C.", state: "Illinois", district: "3", party: "Democratic" },
  { name: "Nunn, Zachary", state: "Iowa", district: "3", party: "Republican" },
  { name: "Moylan, James C.", state: "Guam", district: "0", party: "Republican" },
  { name: "Moskowitz, Jared", state: "Florida", district: "23", party: "Democratic" },
  { name: "Mills, Cory", state: "Florida", district: "7", party: "Republican" },
  { name: "Miller, Max L.", state: "Ohio", district: "7", party: "Republican" },
  { name: "Menendez, Robert", state: "New Jersey", district: "8", party: "Democratic" },
  { name: "McGarvey, Morgan", state: "Kentucky", district: "3", party: "Democratic" },
  { name: "Luna, Anna Paulina", state: "Florida", district: "13", party: "Republican" },
  { name: "Lee, Laurel M.", state: "Florida", district: "15", party: "Republican" },
  { name: "Lawler, Michael", state: "New York", district: "17", party: "Republican" },
  { name: "Langworthy, Nicholas A.", state: "New York", district: "23", party: "Republican" },
  { name: "Landsman, Greg", state: "Ohio", district: "1", party: "Democratic" },
  { name: "LaLota, Nick", state: "New York", district: "1", party: "Republican" },
  { name: "Kean, Thomas H.", state: "New Jersey", district: "7", party: "Republican" },
  { name: "James, John", state: "Michigan", district: "10", party: "Republican" },
  { name: "Jackson, Jonathan L.", state: "Illinois", district: "1", party: "Democratic" },
  { name: "Ivey, Glenn", state: "Maryland", district: "4", party: "Democratic" },
  { name: "Hoyle, Val T.", state: "Oregon", district: "4", party: "Democratic" },
  { name: "Houchin, Erin", state: "Indiana", district: "9", party: "Republican" },
  { name: "Goldman, Daniel S.", state: "New York", district: "10", party: "Democratic" },
  { name: "Foushee, Valerie P.", state: "North Carolina", district: "4", party: "Democratic" },
  { name: "Ezell, Mike", state: "Mississippi", district: "4", party: "Republican" },
  { name: "Edwards, Chuck", state: "North Carolina", district: "11", party: "Republican" },
  { name: "Davis, Donald G.", state: "North Carolina", district: "1", party: "Democratic" },
  { name: "Collins, Mike", state: "Georgia", district: "10", party: "Republican" },
  { name: "Burlison, Eric", state: "Missouri", district: "7", party: "Republican" },
  { name: "Budzinski, Nikki", state: "Illinois", district: "13", party: "Democratic" },
  { name: "Brecheen, Josh", state: "Oklahoma", district: "2", party: "Republican" },
  { name: "Alford, Mark", state: "Missouri", district: "4", party: "Republican" },
  { name: "Ryan, Patrick", state: "New York", district: "18", party: "Democratic" },
  { name: "Miller-Meeks, Mariannette", state: "Iowa", district: "1", party: "Republican" },
  { name: "McClain, Lisa C.", state: "Michigan", district: "9", party: "Republican" },
  { name: "Hinson, Ashley", state: "Iowa", district: "2", party: "Republican" },
  { name: "Gimenez, Carlos A.", state: "Florida", district: "28", party: "Republican" },
  { name: "Tlaib, Rashida", state: "Michigan", district: "12", party: "Democratic" },
  { name: "Tenney, Claudia", state: "New York", district: "24", party: "Republican" },
  { name: "Mast, Brian J.", state: "Florida", district: "21", party: "Republican" },
  { name: "Rutherford, John H.", state: "Florida", district: "5", party: "Republican" },
  { name: "LaHood, Darin", state: "Illinois", district: "16", party: "Republican" },
  { name: "Zinke, Ryan K.", state: "Montana", district: "1", party: "Republican" },
  { name: "Dingell, Debbie", state: "Michigan", district: "6", party: "Democratic" },
  { name: "Moolenaar, John R.", state: "Michigan", district: "2", party: "Republican" },
  { name: "Hudson, Richard", state: "North Carolina", district: "9", party: "Republican" },
  { name: "Frankel, Lois", state: "Florida", district: "22", party: "Democratic" },
  { name: "Huizenga, Bill", state: "Michigan", district: "4", party: "Republican" },
  { name: "Walberg, Tim", state: "Michigan", district: "5", party: "Republican" },
  { name: "Nadler, Jerrold", state: "New York", district: "12", party: "Democratic" },
  { name: "Wasserman Schultz, Debbie", state: "Florida", district: "25", party: "Democratic" },
  { name: "Diaz-Balart, Mario", state: "Florida", district: "26", party: "Republican" },
  { name: "Strong, Dale W.", state: "Alabama", district: "5", party: "Republican" },
  { name: "Pettersen, Brittany", state: "Colorado", district: "7", party: "Democratic" },
  { name: "Mullin, Kevin", state: "California", district: "15", party: "Democratic" },
  { name: "Kamlager-Dove, Sydney", state: "California", district: "37", party: "Democratic" },
  { name: "Garcia, Robert", state: "California", district: "42", party: "Democratic" },
  { name: "Crane, Elijah", state: "Arizona", district: "2", party: "Republican" },
  { name: "Ciscomani, Juan", state: "Arizona", district: "6", party: "Republican" },
  { name: "Bean, Aaron", state: "Florida", district: "4", party: "Republican" },
  { name: "Yakym, Rudy", state: "Indiana", district: "2", party: "Republican" },
  { name: "Finstad, Brad", state: "Minnesota", district: "1", party: "Republican" },
  { name: "Flood, Mike", state: "Nebraska", district: "1", party: "Republican" },
  { name: "Cherfilus-McCormick, Sheila", state: "Florida", district: "20", party: "Democratic" },
  { name: "Carey, Mike", state: "Ohio", district: "15", party: "Republican" },
  { name: "Brown, Shontel M.", state: "Ohio", district: "11", party: "Democratic" },
  { name: "Ellzey, Jake", state: "Texas", district: "6", party: "Republican" },
  { name: "Stansbury, Melanie A.", state: "New Mexico", district: "1", party: "Democratic" },
  { name: "Carter, Troy A.", state: "Louisiana", district: "2", party: "Democratic" },
  { name: "Letlow, Julia", state: "Louisiana", district: "5", party: "Republican" },
  { name: "Obernolte, Jay", state: "California", district: "23", party: "Republican" },
  { name: "Kim, Young", state: "California", district: "40", party: "Republican" },
  { name: "Van Duyne, Beth", state: "Texas", district: "24", party: "Republican" },
  { name: "Strickland, Marilyn", state: "Washington", district: "10", party: "Democratic" },
  { name: "Owens, Burgess", state: "Utah", district: "4", party: "Republican" },
  { name: "Nehls, Troy E.", state: "Texas", district: "22", party: "Republican" },
  { name: "Moore, Blake D.", state: "Utah", district: "1", party: "Republican" },
  { name: "Jacobs, Sara", state: "California", district: "51", party: "Democratic" },
  { name: "Jackson, Ronny", state: "Texas", district: "13", party: "Republican" },
  { name: "Fitzgerald, Scott", state: "Wisconsin", district: "5", party: "Republican" },
  { name: "Williams, Nikema", state: "Georgia", district: "5", party: "Democratic" },
  { name: "Torres, Ritchie", state: "New York", district: "15", party: "Democratic" },
  { name: "Spartz, Victoria", state: "Indiana", district: "5", party: "Republican" },
  { name: "Salazar, Maria Elvira", state: "Florida", district: "27", party: "Republican" },
  { name: "Ross, Deborah K.", state: "North Carolina", district: "2", party: "Democratic" },
  { name: "Pfluger, August", state: "Texas", district: "11", party: "Republican" },
  { name: "Mrvan, Frank J.", state: "Indiana", district: "1", party: "Democratic" },
  { name: "Miller, Mary E.", state: "Illinois", district: "15", party: "Republican" },
  { name: "Mann, Tracey", state: "Kansas", district: "1", party: "Republican" },
  { name: "Malliotakis, Nicole", state: "New York", district: "11", party: "Republican" },
  { name: "Mace, Nancy", state: "South Carolina", district: "1", party: "Republican" },
  { name: "Leger Fernandez, Teresa", state: "New Mexico", district: "3", party: "Democratic" },
  { name: "Harshbarger, Diana", state: "Tennessee", district: "1", party: "Republican" },
  { name: "Garbarino, Andrew R.", state: "New York", district: "2", party: "Republican" },
  { name: "Fischbach, Michelle", state: "Minnesota", district: "7", party: "Republican" },
  { name: "Feenstra, Randy", state: "Iowa", district: "4", party: "Republican" },
  { name: "Fallon, Pat", state: "Texas", district: "4", party: "Republican" },
  { name: "Donalds, Byron", state: "Florida", district: "19", party: "Republican" },
  { name: "Clyde, Andrew S.", state: "Georgia", district: "9", party: "Republican" },
  { name: "Cammack, Kat", state: "Florida", district: "3", party: "Republican" },
  { name: "Bice, Stephanie I.", state: "Oklahoma", district: "5", party: "Republican" },
  { name: "Bentz, Cliff", state: "Oregon", district: "2", party: "Republican" },
  { name: "Auchincloss, Jake", state: "Massachusetts", district: "4", party: "Democratic" },
  { name: "Tiffany, Thomas P.", state: "Wisconsin", district: "7", party: "Republican" },
  { name: "Murphy, Gregory F.", state: "North Carolina", district: "3", party: "Republican" },
  { name: "Golden, Jared F.", state: "Maine", district: "2", party: "Democratic" },
  { name: "Steil, Bryan", state: "Wisconsin", district: "1", party: "Republican" },
  { name: "Schrier, Kim", state: "Washington", district: "8", party: "Democratic" },
  { name: "Garcia, Sylvia R.", state: "Texas", district: "29", party: "Democratic" },
  { name: "Roy, Chip", state: "Texas", district: "21", party: "Republican" },
  { name: "Escobar, Veronica", state: "Texas", district: "16", party: "Democratic" },
  { name: "Fletcher, Lizzie", state: "Texas", district: "7", party: "Democratic" },
  { name: "Gooden, Lance", state: "Texas", district: "5", party: "Republican" },
  { name: "Rose, John W.", state: "Tennessee", district: "6", party: "Republican" },
  { name: "Burchett, Tim", state: "Tennessee", district: "2", party: "Republican" },
  { name: "Johnson, Dusty", state: "South Dakota", district: "0", party: "Republican" },
  { name: "Timmons, William R.", state: "South Carolina", district: "4", party: "Republican" },
  { name: "Reschenthaler, Guy", state: "Pennsylvania", district: "14", party: "Republican" },
  { name: "Joyce, John", state: "Pennsylvania", district: "13", party: "Republican" },
  { name: "Meuser, Daniel", state: "Pennsylvania", district: "9", party: "Republican" },
  { name: "Houlahan, Chrissy", state: "Pennsylvania", district: "6", party: "Democratic" },
  { name: "Dean, Madeleine", state: "Pennsylvania", district: "4", party: "Democratic" },
  { name: "Van Drew, Jefferson", state: "New Jersey", district: "2", party: "Republican" },
  { name: "Craig, Angie", state: "Minnesota", district: "2", party: "Democratic" },
  { name: "García, Jesús G.", state: "Illinois", district: "4", party: "Democratic" },
  { name: "Smucker, Lloyd", state: "Pennsylvania", district: "11", party: "Republican" },
  { name: "Evans, Dwight", state: "Pennsylvania", district: "3", party: "Democratic" },
  { name: "Perry, Scott", state: "Pennsylvania", district: "10", party: "Republican" },
  { name: "Kelly, Mike", state: "Pennsylvania", district: "16", party: "Republican" },
  { name: "Thompson, Glenn", state: "Pennsylvania", district: "15", party: "Republican" },
  { name: "Mfume, Kweisi", state: "Maryland", district: "7", party: "Democratic" },
  { name: "Walkinshaw, James R.", state: "Virginia", district: "11", party: "Democratic" },
  { name: "Ocasio-Cortez, Alexandria", state: "New York", district: "14", party: "Democratic" },
  { name: "Lee, Susie", state: "Nevada", district: "3", party: "Democratic" },
  { name: "Pappas, Chris", state: "New Hampshire", district: "1", party: "Democratic" },
  { name: "Guest, Michael", state: "Mississippi", district: "3", party: "Republican" },
  { name: "Stauber, Pete", state: "Minnesota", district: "8", party: "Republican" },
  { name: "Omar, Ilhan", state: "Minnesota", district: "5", party: "Democratic" },
  { name: "Stevens, Haley M.", state: "Michigan", district: "11", party: "Democratic" },
  { name: "Pressley, Ayanna", state: "Massachusetts", district: "7", party: "Democratic" },
  { name: "Trahan, Lori", state: "Massachusetts", district: "3", party: "Democratic" },
  { name: "Davids, Sharice", state: "Kansas", district: "3", party: "Democratic" },
  { name: "Baird, James R.", state: "Indiana", district: "4", party: "Republican" },
  { name: "Underwood, Lauren", state: "Illinois", district: "14", party: "Democratic" },
  { name: "Casten, Sean", state: "Illinois", district: "6", party: "Democratic" },
  { name: "Fulcher, Russ", state: "Idaho", district: "1", party: "Republican" },
  { name: "Steube, W. Gregory", state: "Florida", district: "17", party: "Republican" },
  { name: "Hayes, Jahana", state: "Connecticut", district: "5", party: "Democratic" },
  { name: "Neguse, Joe", state: "Colorado", district: "2", party: "Democratic" },
  { name: "Levin, Mike", state: "California", district: "49", party: "Democratic" },
  { name: "Hern, Kevin", state: "Oklahoma", district: "1", party: "Republican" },
  { name: "Morelle, Joseph D.", state: "New York", district: "25", party: "Democratic" },
  { name: "Balderson, Troy", state: "Ohio", district: "12", party: "Republican" },
  { name: "Cloud, Michael", state: "Texas", district: "27", party: "Republican" },
  { name: "Gomez, Jimmy", state: "California", district: "34", party: "Democratic" },
  { name: "Norman, Ralph", state: "South Carolina", district: "5", party: "Republican" },
  { name: "Estes, Ron", state: "Kansas", district: "4", party: "Republican" },
  { name: "Jayapal, Pramila", state: "Washington", district: "7", party: "Democratic" },
  { name: "Arrington, Jodey C.", state: "Texas", district: "19", party: "Republican" },
  { name: "Kustoff, David", state: "Tennessee", district: "8", party: "Republican" },
  { name: "Fitzpatrick, Brian K.", state: "Pennsylvania", district: "1", party: "Republican" },
  { name: "Espaillat, Adriano", state: "New York", district: "13", party: "Democratic" },
  { name: "Gottheimer, Josh", state: "New Jersey", district: "5", party: "Democratic" },
  { name: "Bacon, Don", state: "Nebraska", district: "2", party: "Republican" },
  { name: "Bergman, Jack", state: "Michigan", district: "1", party: "Republican" },
  { name: "Raskin, Jamie", state: "Maryland", district: "8", party: "Democratic" },
  { name: "Johnson, Mike", state: "Louisiana", district: "4", party: "Republican" },
  { name: "Higgins, Clay", state: "Louisiana", district: "3", party: "Republican" },
  { name: "Krishnamoorthi, Raja", state: "Illinois", district: "8", party: "Democratic" },
  { name: "Soto, Darren", state: "Florida", district: "9", party: "Democratic" },
  { name: "Correa, J. Luis", state: "California", district: "46", party: "Democratic" },
  { name: "Barragán, Nanette Diaz", state: "California", district: "44", party: "Democratic" },
  { name: "Carbajal, Salud O.", state: "California", district: "24", party: "Democratic" },
  { name: "Horsford, Steven", state: "Nevada", district: "4", party: "Democratic" },
  { name: "Schneider, Bradley Scott", state: "Illinois", district: "10", party: "Democratic" },
  { name: "Webster, Daniel", state: "Florida", district: "11", party: "Republican" },
  { name: "Case, Ed", state: "Hawaii", district: "1", party: "Democratic" },
  { name: "Min, Dave", state: "California", district: "47", party: "Democratic" },
  { name: "Hurd, Jeff", state: "Colorado", district: "3", party: "Republican" },
  { name: "Biggs, Andy", state: "Arizona", district: "5", party: "Republican" },
  { name: "Khanna, Ro", state: "California", district: "17", party: "Democratic" },
  { name: "Comer, James", state: "Kentucky", district: "1", party: "Republican" },
  { name: "Davidson, Warren", state: "Ohio", district: "8", party: "Republican" },
  { name: "Kelly, Trent", state: "Mississippi", district: "1", party: "Republican" },
  { name: "Grothman, Glenn", state: "Wisconsin", district: "6", party: "Republican" },
  { name: "Newhouse, Dan", state: "Washington", district: "4", party: "Republican" },
  { name: "Plaskett, Stacey E.", state: "Virgin Islands", district: "0", party: "Democratic" },
  { name: "Beyer, Donald S.", state: "Virginia", district: "8", party: "Democratic" },
  { name: "Babin, Brian", state: "Texas", district: "36", party: "Republican" },
  { name: "Stefanik, Elise M.", state: "New York", district: "21", party: "Republican" },
  { name: "Watson Coleman, Bonnie", state: "New Jersey", district: "12", party: "Democratic" },
  { name: "Rouzer, David", state: "North Carolina", district: "7", party: "Republican" },
  { name: "Emmer, Tom", state: "Minnesota", district: "6", party: "Republican" },
  { name: "Moulton, Seth", state: "Massachusetts", district: "6", party: "Democratic" },
  { name: "Bost, Mike", state: "Illinois", district: "12", party: "Republican" },
  { name: "Allen, Rick W.", state: "Georgia", district: "12", party: "Republican" },
  { name: "Loudermilk, Barry", state: "Georgia", district: "11", party: "Republican" },
  { name: "Carter, Earl L.", state: "Georgia", district: "1", party: "Republican" },
  { name: "Torres, Norma J.", state: "California", district: "35", party: "Democratic" },
  { name: "Westerman, Bruce", state: "Arkansas", district: "4", party: "Republican" },
  { name: "Hill, J. French", state: "Arkansas", district: "2", party: "Republican" },
  { name: "Radewagen, Aumua Amata Coleman", state: "American Samoa", district: "0", party: "Republican" },
  { name: "Palmer, Gary J.", state: "Alabama", district: "6", party: "Republican" },
  { name: "Norcross, Donald", state: "New Jersey", district: "1", party: "Democratic" },
  { name: "Adams, Alma S.", state: "North Carolina", district: "12", party: "Democratic" },
  { name: "Clark, Katherine M.", state: "Massachusetts", district: "5", party: "Democratic" },
  { name: "Smith, Jason", state: "Missouri", district: "8", party: "Republican" },
  { name: "Barr, Andy", state: "Kentucky", district: "6", party: "Republican" },
  { name: "Clarke, Yvette D.", state: "New York", district: "9", party: "Democratic" },
  { name: "Tonko, Paul", state: "New York", district: "20", party: "Democratic" },
  { name: "Kelly, Robin L.", state: "Illinois", district: "2", party: "Democratic" },
  { name: "Meeks, Gregory W.", state: "New York", district: "5", party: "Democratic" },
  { name: "Velázquez, Nydia M.", state: "New York", district: "7", party: "Democratic" },
  { name: "Turner, Michael R.", state: "Ohio", district: "10", party: "Republican" },
  { name: "Tran, Derek", state: "California", district: "45", party: "Democratic" },
  { name: "Pocan, Mark", state: "Wisconsin", district: "2", party: "Democratic" },
  { name: "Veasey, Marc A.", state: "Texas", district: "33", party: "Democratic" },
  { name: "Williams, Roger", state: "Texas", district: "25", party: "Republican" },
  { name: "Weber, Randy K. Sr.", state: "Texas", district: "14", party: "Republican" },
  { name: "Joyce, David P.", state: "Ohio", district: "14", party: "Republican" },
  { name: "Beatty, Joyce", state: "Ohio", district: "3", party: "Democratic" },
  { name: "Jeffries, Hakeem S.", state: "New York", district: "8", party: "Democratic" },
  { name: "Meng, Grace", state: "New York", district: "6", party: "Democratic" },
  { name: "Brownley, Julia", state: "California", district: "26", party: "Democratic" },
  { name: "Huffman, Jared", state: "California", district: "2", party: "Democratic" },
  { name: "DelBene, Suzan K.", state: "Washington", district: "1", party: "Democratic" },
  { name: "Massie, Thomas", state: "Kentucky", district: "4", party: "Republican" },
  { name: "Bonamici, Suzanne", state: "Oregon", district: "1", party: "Democratic" },
  { name: "Amodei, Mark E.", state: "Nevada", district: "2", party: "Republican" },
  { name: "Wittman, Robert J.", state: "Virginia", district: "1", party: "Republican" },
  { name: "Griffith, H. Morgan", state: "Virginia", district: "9", party: "Republican" },
  { name: "DesJarlais, Scott", state: "Tennessee", district: "4", party: "Republican" },
  { name: "Fleischmann, Charles J.", state: "Tennessee", district: "3", party: "Republican" },
  { name: "Harris, Andy", state: "Maryland", district: "1", party: "Republican" },
  { name: "Keating, William R.", state: "Massachusetts", district: "9", party: "Democratic" },
  { name: "Scott, Austin", state: "Georgia", district: "8", party: "Republican" },
  { name: "Wilson, Frederica S.", state: "Florida", district: "24", party: "Democratic" },
  { name: "Womack, Steve", state: "Arkansas", district: "3", party: "Republican" },
  { name: "Sewell, Terri A.", state: "Alabama", district: "7", party: "Democratic" },
  { name: "Cohen, Steve", state: "Tennessee", district: "9", party: "Democratic" },
  { name: "Jordan, Jim", state: "Ohio", district: "4", party: "Republican" },
  { name: "Buchanan, Vern", state: "Florida", district: "16", party: "Republican" },
  { name: "Castor, Kathy", state: "Florida", district: "14", party: "Democratic" },
  { name: "Bilirakis, Gus M.", state: "Florida", district: "12", party: "Republican" },
  { name: "Quigley, Mike", state: "Illinois", district: "5", party: "Democratic" },
  { name: "Titus, Dina", state: "Nevada", district: "1", party: "Democratic" },
  { name: "Pingree, Chellie", state: "Maine", district: "1", party: "Democratic" },
  { name: "Guthrie, Brett", state: "Kentucky", district: "2", party: "Republican" },
  { name: "Himes, James A.", state: "Connecticut", district: "4", party: "Democratic" },
  { name: "Scalise, Steve", state: "Louisiana", district: "1", party: "Republican" },
  { name: "Foster, Bill", state: "Illinois", district: "11", party: "Democratic" },
  { name: "Carson, André", state: "Indiana", district: "7", party: "Democratic" },
  { name: "McGovern, James P.", state: "Massachusetts", district: "2", party: "Democratic" },
  { name: "Neal, Richard E.", state: "Massachusetts", district: "1", party: "Democratic" },
  { name: "Moore, Gwen", state: "Wisconsin", district: "4", party: "Democratic" },
  { name: "Scott, David", state: "Georgia", district: "13", party: "Democratic" },
  { name: "Sánchez, Linda T.", state: "California", district: "38", party: "Democratic" },
  { name: "Lynch, Stephen F.", state: "Massachusetts", district: "8", party: "Democratic" },
  { name: "Simon, Lateefah", state: "California", district: "12", party: "Democratic" },
  { name: "Randall, Emily", state: "Washington", district: "6", party: "Democratic" },
  { name: "Rivas, Luz M.", state: "California", district: "29", party: "Democratic" },
  { name: "Liccardo, Sam T.", state: "California", district: "16", party: "Democratic" },
  { name: "Hamadeh, Abraham J.", state: "Arizona", district: "8", party: "Republican" },
  { name: "Gray, Adam", state: "California", district: "13", party: "Democratic" },
  { name: "Begich, Nicholas J.", state: "Alaska", district: "0", party: "Republican" },
  { name: "Ansari, Yassamin", state: "Arizona", district: "3", party: "Democratic" },
  { name: "Smith, Adrian", state: "Nebraska", district: "3", party: "Republican" },
  { name: "Johnson, Henry C.", state: "Georgia", district: "4", party: "Democratic" },
  { name: "Courtney, Joe", state: "Connecticut", district: "2", party: "Democratic" },
  { name: "Pallone, Frank", state: "New Jersey", district: "6", party: "Democratic" },
  { name: "Simpson, Michael K.", state: "Idaho", district: "2", party: "Republican" },
  { name: "Schakowsky, Janice D.", state: "Illinois", district: "9", party: "Democratic" },
  { name: "Larson, John B.", state: "Connecticut", district: "1", party: "Democratic" },
  { name: "Smith, Adam", state: "Washington", district: "9", party: "Democratic" },
  { name: "DeGette, Diana", state: "Colorado", district: "1", party: "Democratic" },
  { name: "Davis, Danny K.", state: "Illinois", district: "7", party: "Democratic" },
  { name: "Aderholt, Robert B.", state: "Alabama", district: "4", party: "Republican" },
  { name: "Thompson, Bennie G.", state: "Mississippi", district: "2", party: "Democratic" },
  { name: "Smith, Christopher H.", state: "New Jersey", district: "4", party: "Republican" },
  { name: "Scott, Robert C.", state: "Virginia", district: "3", party: "Democratic" },
  { name: "Rogers, Harold", state: "Kentucky", district: "5", party: "Republican" },
  { name: "Bishop, Sanford D.", state: "Georgia", district: "2", party: "Democratic" },
  { name: "Lucas, Frank D.", state: "Oklahoma", district: "3", party: "Republican" },
  { name: "Cuellar, Henry", state: "Texas", district: "28", party: "Democratic" },
  { name: "McCaul, Michael T.", state: "Texas", district: "10", party: "Republican" },
  { name: "Foxx, Virginia", state: "North Carolina", district: "5", party: "Republican" },
  { name: "Cleaver, Emanuel", state: "Missouri", district: "5", party: "Democratic" },
  { name: "Carter, John R.", state: "Texas", district: "31", party: "Republican" },
  { name: "Cole, Tom", state: "Oklahoma", district: "4", party: "Republican" },
  { name: "Rogers, Mike D.", state: "Alabama", district: "3", party: "Republican" },
  { name: "Wilson, Joe", state: "South Carolina", district: "2", party: "Republican" },
  { name: "Larsen, Rick", state: "Washington", district: "2", party: "Democratic" },
  { name: "Graves, Sam", state: "Missouri", district: "6", party: "Republican" },
  { name: "McCollum, Betty", state: "Minnesota", district: "4", party: "Democratic" },
  { name: "Clyburn, James E.", state: "South Carolina", district: "6", party: "Democratic" },
  { name: "Kaptur, Marcy", state: "Ohio", district: "9", party: "Democratic" },
  { name: "Sessions, Pete", state: "Texas", district: "17", party: "Republican" },
  { name: "Issa, Darrell", state: "California", district: "48", party: "Republican" },
  { name: "Calvert, Ken", state: "California", district: "41", party: "Republican" },
  { name: "Lofgren, Zoe", state: "California", district: "18", party: "Democratic" },
  { name: "Panetta, Jimmy", state: "California", district: "19", party: "Democratic" },
  { name: "Valadao, David G.", state: "California", district: "22", party: "Republican" },
  { name: "Sherman, Brad", state: "California", district: "32", party: "Democratic" },
  { name: "Thompson, Mike", state: "California", district: "4", party: "Democratic" },
  { name: "Matsui, Doris O.", state: "California", district: "7", party: "Democratic" },
  { name: "McClintock, Tom", state: "California", district: "5", party: "Republican" },
  { name: "Schweikert, David", state: "Arizona", district: "1", party: "Republican" },
  { name: "Garamendi, John", state: "California", district: "8", party: "Democratic" },
  { name: "Chu, Judy", state: "California", district: "28", party: "Democratic" },
  { name: "Gosar, Paul A.", state: "Arizona", district: "9", party: "Republican" },
  { name: "DeSaulnier, Mark", state: "California", district: "10", party: "Democratic" },
  { name: "Aguilar, Pete", state: "California", district: "33", party: "Democratic" },
  { name: "Lieu, Ted", state: "California", district: "36", party: "Democratic" },
  { name: "Torres, Norma J.", state: "California", district: "35", party: "Democratic" },
  { name: "Brownley, Julia", state: "California", district: "26", party: "Democratic" },
  { name: "Ruiz, Raul", state: "California", district: "25", party: "Democratic" },
  { name: "Takano, Mark", state: "California", district: "39", party: "Democratic" },
  { name: "Vargas, Juan", state: "California", district: "52", party: "Democratic" },
  { name: "Peters, Scott H.", state: "California", district: "50", party: "Democratic" },
  { name: "Bera, Ami", state: "California", district: "6", party: "Democratic" },
  { name: "Harder, Josh", state: "California", district: "9", party: "Democratic" },
  { name: "Stanton, Greg", state: "Arizona", district: "4", party: "Democratic" },
  { name: "Scanlon, Mary Gay", state: "Pennsylvania", district: "5", party: "Democratic" },
  { name: "Gonzalez, Vicente", state: "Texas", district: "34", party: "Democratic" },
  { name: "Green, Al", state: "Texas", district: "9", party: "Democratic" },
  { name: "Doggett, Lloyd", state: "Texas", district: "37", party: "Democratic" },
  // Additional members from other fetches
  { name: "Hoyer, Steny H.", state: "Maryland", district: "5", party: "Democratic" },
  { name: "Pelosi, Nancy", state: "California", district: "11", party: "Democratic" },
  { name: "Rogers, Harold", state: "Kentucky", district: "5", party: "Republican" },
];

function parseLastFirst(nameStr) {
  // Handle "Last, First M." format
  const parts = nameStr.split(",").map((s) => s.trim());
  if (parts.length < 2) return nameStr;
  const last = parts[0];
  const first = parts.slice(1).join(", ");
  return `${first} ${last}`;
}

function normalizeParty(p) {
  if (!p) return "?";
  const lower = p.toLowerCase();
  if (lower.startsWith("dem")) return "D";
  if (lower.startsWith("rep")) return "R";
  if (lower.startsWith("ind")) return "I";
  return p.charAt(0).toUpperCase();
}

function getWebsiteUrl(fullName, lastName) {
  // Check overrides first
  for (const [key, url] of Object.entries(WEBSITE_OVERRIDES)) {
    if (
      key === fullName ||
      key.replace(/[,.''\-]/g, "").toLowerCase() ===
        fullName.replace(/[,.''\-]/g, "").toLowerCase()
    ) {
      return url;
    }
  }

  // Default: lastname.house.gov
  const cleanLast = lastName
    .toLowerCase()
    .replace(/[^a-z]/g, "")
    .trim();
  return `https://${cleanLast}.house.gov`;
}

// Deduplicate by state+district
const seen = new Map();

for (const raw of rawMembers) {
  const fullName = parseLastFirst(raw.name);
  const state = STATE_ABBR[raw.state] || raw.state;
  const district = raw.district ? String(raw.district) : "0";
  const party = normalizeParty(raw.party);

  const key = `${state}-${district}`;

  // Extract last name for URL generation
  const nameParts = raw.name.split(",");
  const lastName = nameParts[0].trim();

  const websiteUrl = getWebsiteUrl(fullName, lastName);

  if (!seen.has(key)) {
    seen.set(key, {
      full_name: fullName,
      state,
      district: district === "0" ? "At-Large" : parseInt(district),
      party,
      website_url: websiteUrl,
    });
  }
}

const members = Array.from(seen.values()).sort((a, b) => {
  if (a.state !== b.state) return a.state.localeCompare(b.state);
  const da = typeof a.district === "number" ? a.district : 0;
  const db = typeof b.district === "number" ? b.district : 0;
  return da - db;
});

console.log(`Total unique members: ${members.length}`);

// Write output
const outPath = path.join(__dirname, "house_raw.json");
fs.writeFileSync(outPath, JSON.stringify(members, null, 2));
console.log(`Written to ${outPath}`);
